export const START_FETCH = 'START_FETCH'
export const FETCH_SUCCESS = 'FETCH_ACCSESS'
export const ERROR_CATCHED = 'ERROR_CATCHED'
export const INPUT_EDIT = 'INPUT_EDIT'
export const TOGGLE_MODE ='TOGGLE_MODE'

